version: '3.4'
services:
  microservice:
    ports:
      - "21767:21767"
    image: vetch
    depends_on:
      - "couchserver"

  couchserver:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
      - ./dbdata:/opt/couchdb/data

